# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20150930_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='code',
            field=models.CharField(default=users.models.gen_randcode, max_length=32),
        ),
        migrations.AlterField(
            model_name='passreset',
            name='code',
            field=models.CharField(default=users.models.gen_randcode, max_length=32),
        ),
    ]
