from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

from judge import views

urlpatterns = [
    url(r'^$', views.ProblemList.as_view(), 
        name = 'problem_list'),
    url(r'^problems/page/(?P<page>\d+)/$', views.ProblemList.as_view(), 
        name = 'problem_page'),
    url(r'^problems/tags/(?P<tags>[\w ]+(,[\w ]+)*)/$', 
        views.ProblemList.as_view(), name = 'problem_list_tags'),
    url(r'^problems/tags/(?P<tags>[\w ]+(,[\w ]+)*)/page/(?P<page>\d+)/$', 
        views.ProblemList.as_view(), name = 'problem_list_tags_page'),
    url(r'^problems/filter/$', views.ProblemFilter.as_view(),
        name = 'problem_filter'),
    url(r'^problems/(?P<pk>\d+)/$', views.ProblemDetails.as_view(), 
       name = 'problem_details'),

    url(r'^problems/new/', views.ProblemNew.as_view(), 
        name = 'problem_new'),
    url(r'^problems/(?P<pk>\d+)/edit/$', views.ProblemEdit.as_view(), 
        name = 'problem_edit'),
    url(r'^problems/(?P<pk>\d+)/delete/$', views.ProblemDelete.as_view(),
       name = 'problem_delete'),
    url(r'^problems/(?P<pk>\d+)/media/$', views.ProblemMedia.as_view(),
        name = 'problem_media'),
    url(r'^problems/(?P<pk>\d+)/retest/$', views.ProblemRetest.as_view(),
       name = 'problem_retest'),
    url(r'^problems/(?P<pk>\d+)/visibility/$', 
        views.ProblemVisibility.as_view(), name = 'problem_visibility'),
    url(r'^problems/(?P<pk>\d+)/checker/$', views.ProblemChecker.as_view(),
        name = 'problem_checker'),
    url(r'^problems/import/$', views.PorblemImport.as_view(),
        name = 'problem_import'),
    url(r'problems/(?P<pk>\d+)/export/$', views.ProblemExport.as_view(),
        name = 'problem_export'),

    url(r'^problems/(?P<problem_id>\d+)/newtest/$', views.TestNew.as_view(), 
       name = 'test_new'),
    url(r'^problems/(?P<problem_id>\d+)/tests/$', views.TestList.as_view(),
       name = 'test_list'),
    url(r'^test/(?P<pk>\d+)/edit/$', views.TestEdit.as_view(),
       name = 'test_edit'),
    url(r'^test/(?P<ids>\d+(,\d+)*)/delete/$', views.TestDelete.as_view(),
        name = 'test_delete'),
    url(r'^test/(?P<pk>\d+)/input/$', views.TestInput.as_view(),
        name = 'test_input'),
    url(r'^test/(?P<pk>\d+)/output/$', views.TestOutput.as_view(),
        name = 'test_output'),

    url(r'^problems/(?P<problem_id>\d+)/newtestgroup/$',
            views.TestGroupNew.as_view(), name = 'test_group_new'),
    url(r'^testgroup/(?P<pk>\d+)/edit/$',
            views.TestGroupEdit.as_view(), name = 'test_group_edit'),
    url(r'^testgroup/(?P<pk>\d+)/delete/$',
            views.TestGroupDelete.as_view(), name = 'test_group_delete'),

    url(r'^problems/(?P<pk>\d+)/submit/$', views.SolutionSubmit.as_view(), 
        name = 'solution_submit'),
    url(r'^solutions/(?P<pk>\d+)/$', views.SolutionDetails.as_view(),
        name = 'solution_details'),
    url(r'^solutions/(?P<pk>\d+)/source/$', views.SolutionSource.as_view(),
        name = 'solution_source'),
]
