# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0029_auto_20151206_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name of test group')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Points')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='TestGroupResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=True)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Solution')),
                ('test_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.TestGroup')),
            ],
            options={
                'ordering': ['test_group'],
            },
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-test_group', 'pk'], 'permissions': (('view_test', 'Can see input/output files'),)},
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='customChecker',
            new_name='custom_checker',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='maxScore',
            new_name='max_score',
        ),
        migrations.RenameField(
            model_name='userproblemdata',
            old_name='maxScore',
            new_name='max_score',
        ),
        migrations.RenameField(
            model_name='userstatts',
            old_name='solvedProblems',
            new_name='solved_problems',
        ),
        migrations.RenameField(
            model_name='userstatts',
            old_name='triedProblems',
            new_name='tried_problems',
        ),
        migrations.AddField(
            model_name='testresult',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AddField(
            model_name='testgroup',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Problem'),
        ),
        migrations.AddField(
            model_name='test',
            name='test_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='judge.TestGroup'),
        ),
    ]
