# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0031_auto_20151208_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['pk'], 'permissions': (('view_test', 'Can see input/output files'),)},
        ),
    ]
