# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0033_auto_20151208_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='judge.TestGroup'),
        ),
    ]
