# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0034_auto_20151210_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGroupResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Points')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Solution')),
                ('test_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.TestGroup')),
            ],
            options={
                'ordering': ['test_group'],
            },
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
