# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0036_auto_20151210_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='customChecker',
            new_name='custom_checker',
        ),
    ]
