# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0040_auto_20151212_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testgroupresult',
            name='passed',
            field=models.BooleanField(default=True),
        ),
    ]
