# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0041_auto_20151212_2254'),
        ('judge', '0030_auto_20151212_2334'),
    ]

    operations = [
    ]
