# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0041_auto_20151212_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='testgroupresult',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_group_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.TestGroupResult'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_limit',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Time limit (sec)'),
        ),
        migrations.AlterField(
            model_name='userproblemdata',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
