# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0043_auto_20151213_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testgroupresult',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
