# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0048_auto_20151220_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstatts',
            options={'verbose_name': 'User statistic', 'verbose_name_plural': 'User statistics'},
        ),
        migrations.AlterField(
            model_name='test',
            name='time_limit',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Time limit (sec)'),
        ),
    ]
