# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0049_auto_20151220_1436'),
        ('judge', '0049_auto_20151224_1212'),
    ]

    operations = [
    ]
