# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-21 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0050_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-id'], 'permissions': (('retest_problem', 'Can start a retest'), ('change_visibility_of_problem', 'Can change the visibility of a problem'), ('see_hidden_problems', 'Can see hidden problems'), ('add_media_to_problem', 'Can upload media for a problem'), ('add_checker_to_problem', 'Can add a checker for a problem'), ('add_grader_to_problem', 'Can add a custom grader for a problem'), ('import_problem', 'Can import problems'))},
        ),
        migrations.AddField(
            model_name='problem',
            name='custom_grader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='grader_header',
            field=models.TextField(blank=True, verbose_name='Grader header code'),
        ),
        migrations.AddField(
            model_name='problem',
            name='grader_header_file_name',
            field=models.CharField(blank=True, max_length=32, verbose_name='Filename for the grader header         file'),
        ),
        migrations.AddField(
            model_name='problem',
            name='grader_source',
            field=models.TextField(blank=True, verbose_name='Grader source code'),
        ),
    ]
