# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-21 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0051_auto_20160521_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='grader_header_file_name',
            new_name='grader_header_filename',
        ),
    ]
