# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 07:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0052_auto_20160521_1943'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserStatts',
            new_name='UserStats',
        ),
        migrations.AlterField(
            model_name='solution',
            name='submit_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of submition'),
        ),
        migrations.AlterField(
            model_name='userproblemdata',
            name='last_submit',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
