# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 07:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0053_auto_20161005_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproblemdata',
            name='last_submit',
            field=models.DateTimeField(default=datetime.datetime(1999, 12, 31, 22, 3, tzinfo=utc)),
        ),
    ]
