# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0054_auto_20161005_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='compilation_status',
            field=models.CharField(choices=[('pending', 'Not yet compiled'), ('success', 'Compilation successful'), ('syntax', 'Compilation failed (syntax error)'), ('tl', 'Compilation failed (time limit exceeed')], default='pending', max_length=8, verbose_name='Compilation status'),
        ),
    ]
