# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20150707_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_language',
            field=models.CharField(choices=[('html', 'HTML'), ('md', 'Markdown')], default='html', max_length=8, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
