# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20151219_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-post_time',), 'permissions': (('change_foreign_blogpost', "Edit someone else's post"),)},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='New Draft', max_length=64, verbose_name='Title'),
        ),
    ]
