# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0004_mediafile_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='filename',
            field=models.CharField(max_length=64),
        ),
    ]
